global:
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  service:
    type: NodePort
    port: 3000
  datasources:
    enabled: true
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus-ds
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local:80
          access: proxy
          isDefault: true
          editable: true
  

