apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-node-config
  namespace: bitcoin-node
data:
  bitcoin.conf: |
    testnet=1
    printtoconsole=1
    rpcbind=0.0.0.0
    rpcallowip=0.0.0.0/0
    rpcport=8332
    rpcuser=${BITCOIN_RPC_USER}
    rpcpassword=${BITCOIN_RPC_PASSWORD}
    prune=550
    server=1
