apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-node-config
  namespace: bitcoin-node
data:
  bitcoin.conf: |
    testnet4=1
    printtoconsole=1
    rpcallowip=0.0.0.0/0
    rpcuser=$BITCOIN_RPC_USER
    rpcpassword=$BITCOIN_RPC_PASSWORD
    prune=550
    server=1
    [test]
    rpcbind=0.0.0.0
    rpcport=18332
