---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitcoin-node

resources:
  - statefulset.yaml
  - service.yaml
  - secrets.yaml

  - configmap.yaml

commonLabels:
  app: bitcoin-node