---
# using default here since I'm using local k8s cluster
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: bitcoin-node-data-pvc
#   namespace: bitcoin-node
# spec:
#   accessModes: ["ReadWriteOnce"]
#   storageClassName: "default" 
#   resources:
#     requests:
#       storage: 10Gi 