apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-node-secrets
  namespace: bitcoin-node
  labels:
    app: bitcoin-node
data:
  bitcoin_rpc_password: TkRFellUUXpZamszT1RjNVpERm1abUppTVRCaE5XTTMK 
  bitcoin_rpc_user: YWRlZGF5bwo=
