apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-node
  namespace: bitcoin-node
spec:
  serviceName: bitcoin-node
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-node
  template:
    metadata:
      labels:
        app: bitcoin-node
    spec:
      containers:
      - name: bitcoin-node
        image: bitcoin/bitcoin:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: 2
        args: 
          - -testnet=1
          - -rpcbind=0.0.0.0
          - -rpcallowip=0.0.0.0/0
          - -rpcport=18332
          - -rpcuser=${BITCOIN_RPC_USER}
          - -rpcpassword=${BITCOIN_RPC_PASSWORD}
          - -prune=1000
        ports:
        - containerPort: 18332
          name: rpc
        - containerPort: 8333
          name: p2p
        env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              name: bitcoin-node-secrets
              key: bitcoin_rpc_user
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitcoin-node-secrets
              key: bitcoin_rpc_password
        volumeMounts:
        - name: bitcoin-data
          mountPath: /home/bitcoin/data
      volumes:
      - name: bitcoin-data
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: hostpath # change to appropriate storage class for production
      resources:
        requests:
          storage: 20Gi 
