---
all:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_port: 22
      ansible_connection: local
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_password: "{{ lookup('env', 'ANSIBLE_SUDO_PASS') }}"
      ansible_python_interpreter: /usr/bin/python3
  vars:
    target_os: "macos"
    minikube_version: "1.32.0"
    minikube_install_path: "/usr/local/bin/minikube"
    system_arch: "arm64"