---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitcoin-node-exporter

resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml

commonLabels:
  app: bitcoin-node-exporter